trying this...

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -21,4 +21,4 @@ jobs:
       with:
         java-version: 1.8
     - name: Build with Maven
-      run: mvn formatter:validate && mvn -B package --file pom.xml
+      run: ([[ -z $(git status -s) ]] && (echo "tree is clean";exit 0) || (echo "tree is dirty";exit 1)) && mvn -B package --file pom.xml || (echo "Failure!";exit 1)
